version: '3.8'

services:
  dev:
      container_name: lgt_location_dev
      image: nestjs-api-dev:1.0.0
      build:
          context: .
          target: development
          dockerfile: DOCKERFILE
      command: npm run start:debug
      ports:
          - 9001:9000
      networks:
          - nesjs-network
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped
  prod:
      container_name: lgt_location_prod
      image: nestjs-api-prod:1.0.0
      build:
          context: .
          target: production
          dockerfile: DOCKERFILE
      command: npm run start:prod
      ports:
          - 9000:9000
      networks:
          - nesjs-network
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped
networks:
  nesjs-network: